### ISSUE TITLE
Sept 2024 Updates

### ISSUE THREAD

**Issue by ryan-jan** [hrkowalewska/site#1]
## About

My research examines women's employment across industrialised countries and how social policies reduce or potentially increase gender inequalities in paid work. I currently hold a BA/Leverhulme Small Research Grant for a project looking at older women's labour market experiences and have recently completed a New Investigator Grant funded by the Economic and Social Research Council.

My research has been published in European Sociological Review, Work, Employment & Society, Journal of European Social Policy, Journal of Social Policy, and Social Policy & Society and has been featured in the media, such as in The Independent.

A copy of my CV is located here.

## New project

Too old to hire, too young to retire? Women’s job-seeking experiences after age 50

Women’s experiences of re-entering employment in later life remain largely invisible in academic research and society. This project will spotlight these experiences through in-depth, qualitative interviews with unemployed/inactive women aged 50-65 who are seeking re-employment across England. Studies have considered previous cohorts, but not these late-Boomer and early-Gen-X women. These women were a turning point in women’s employment rights and expectations; yet, many have no choice but to work for longer amid UK State Pension Age increases, welfare cuts, the cost-of-living crisis, and pension privatisation. The biographical approach will highlight the influence of earlier life events on these women’s labour market experiences today, while its intersectional approach will elucidate differences by class, family status, and ethnicity.

This project is funded by a British Academy/Leverhulme Small Research Grant (SRG24\240203) and will run from January 2025 for 24 months.

## Grants & Prizes

BA/Leverhulme Small Research Grant
University of Bath - Jan 2025
Principal Investigator on the project, ‘Too Old to Hire, Too Young to Retire? Women’s Job-Seeking Experiences After Age 50.'

**Comment by hrkowalewska** [comment]
@hrkowalewska Can you find a picture to use for this new project please and link it/attach it here.

**Comment by hrkowalewska** [comment]
![image](https://github.com/user-attachments/assets/6378b70f-0e72-43c5-9c47-467803a129f5)
